### ISSUE TITLE
Feature Request: Velocity Support

### ISSUE THREAD

**Issue by JustinDevB** [Dablakbandit/always-online#11]
Please add support for Velocity. It is quickly gaining traction as a replacement for Bungee. (It has even joined Paper)
https://velocitypowered.com/

**Comment by GeleVla** [comment]
+1

Velocity is increasing in popularity and support for waterfall will soon be deprecated.

**Comment by Dablakbandit** [comment]
@JustinDevB @GeleVla Can you try this version?
https://github.com/Dablakbandit/always-online/raw/velocity/output/always-online-latest.jar

**Comment by GeleVla** [comment]
Hi, 

What a coincidence that Mojangs servers are down now ;)
I will try it when they are back online and let you know if it works!

**Comment by GeleVla** [comment]
I installed it, of couse the Mojang servers are down.
It loaded correctly, but then it started to give errors.

Log: https://bin.bloom.host/juyibepefo

**Comment by GeleVla** [comment]
No more issues after the Mojang servers are online!

**Comment by GeleVla** [comment]
> No more issues after the Mojang servers are online!

But when enabling MySQL a new error occured.

https://bin.bloom.host/ihapoliduc

**Comment by Dablakbandit** [comment]
Velocity doesn't seem to come with MySQL connector, there are some examples on their forums as for how to get this loaded with velocity.

As for the errors, I have pushed an update to the same link as posted above.

**Comment by GeleVla** [comment]
Hi, there are pluginis that use MySQL on Velocity. Like Plan and Luckperms. 

Can you take a second look to see if you can implement it within the plugin?

**Comment by Dablakbandit** [comment]
I would rather not bundle it as it would bloat the jar file.

**Comment by GeleVla** [comment]
The size of the jar file doesn't matter much, does it?

**Comment by Dablakbandit** [comment]
If each plugin adds the mysql connector, then you can get conflicting versions/classes, alongside bloating the jar.

**Comment by GeleVla** [comment]
So how do I enable it? I don't know which forum post your meant.

**Comment by Dablakbandit** [comment]
https://forums.velocitypowered.com/t/plan-and-velocity-mysql/220/4

**Comment by GeleVla** [comment]
Hi, I will look into it. Did you made the changes for Velocity also on the GitHub files?

**Comment by GeleVla** [comment]
Hi, I tried using the new flags and with the mysql jar in the main folder. But still I get an error. Could you make a second jar for velocity only?

`java -Xms128M -Xmx1000M -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15 -Dterminal.jline=false -Dterminal.ansi=true -cp "velocity.jar:mysql-connector-java-8.0.16.jar"com.velocitypowered.proxy.Velocity -jar velocity.jar`

Logs: https://bin.bloom.host/jelizoqixu

**Comment by GeleVla** [comment]
Any update on this?

**Comment by Dablakbandit** [comment]
Can you try the link again, I've added an option to add jars to /plugins/alwaysonline/libs

Note:
mysql-connector-java also requires protobuf-java

**Comment by GeleVla** [comment]
Hi, I will use the newest version! If I come across any errors I will let you know!

As far for the MySQL, can’t you implement the driver with the plugin? There are plugins that support MySQL on Velocity, like plan and luckperms. Just an idea! ;)

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Dablakbandit ***@***.***>
Verzonden: Wednesday, March 16, 2022 9:14:07 PM
Aan: Dablakbandit/always-online ***@***.***>
CC: Arjan ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Dablakbandit/always-online] Feature Request: Velocity Support (Issue #11)


Velocity doesn't seem to come with MySQL connector, there are some examples on their forums as for how to get this loaded with velocity.

As for the errors, I have pushed an update to the same link as posted above.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDablakbandit%2Falways-online%2Fissues%2F11%23issuecomment-1069575853&data=04%7C01%7C%7C6a32fa4c7d0e4d4c962c08da078986c5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637830584501830763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zWjmDQ2ic%2F1H3h7TG%2F%2BOUDG6Xk%2F51wRNmAljjUFvK9A%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFRV5FG2CGACOXJ4PT57W4DVAI6I7ANCNFSM5PRXJ2HA&data=04%7C01%7C%7C6a32fa4c7d0e4d4c962c08da078986c5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637830584501830763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=R%2BavjJh3mmlYB9MtbkFx02mdD3i2wEeNNCEmUGrTE3g%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C6a32fa4c7d0e4d4c962c08da078986c5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637830584501830763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hd%2F%2BzvLIy4o%2FAHPDk3WuR75fT400DdGNbisMlKYnKm0%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C6a32fa4c7d0e4d4c962c08da078986c5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637830584501830763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KFwYZ4TOEnXEwG61teYp5%2Fd3nSxotHBzIuA8nzmVlp4%3D&reserved=0>.

**Comment by TheKrafter** [comment]
Hey @GeleVla have you run into any more issues or does this seem like its working well so far (besides MySQL support)?

**Comment by EmanYm** [comment]
@TheKrafter 
Even though you necro'd a year old thread, the solution is a library called MySQLDriver.  Another plugin called "VotingPlugin" requires this library to function on a proxy.
You can find it [here](https://bencodez.com/job/MySQLDriver/).
I recently removed VotingPlugin and its dependencies to find a fault somewhere, and discovered that AlwaysOnline would not load without the library.
I hope this helps someone.

**Comment by Dablakbandit** [comment]
Plugin now supports mysql in velocity by default:
https://github.com/Dablakbandit/always-online/raw/master/output/always-online-latest.jar

Waiting to post to spigot after bukkit approval
