### ISSUE TITLE
Always Online does not detect Mojang session server offline.

### ISSUE THREAD

**Issue by Pantera07** [Dablakbandit/always-online#16]
https://twitter.com/MojangStatus/status/1564526594907062273?cxt=HHwWgoCyscOpqLYrAAAA
![1](https://user-images.githubusercontent.com/89838384/187392864-9bd421a3-0f63-4a36-a1a1-b420eb579284.png)

Always Online does not detect Mojang **session** server offline.
The auth server was online, but the seesion server was offline.

Is Always Online only checking the auth server?

**Comment by Pantera07** [comment]
https://github.com/Dablakbandit/always-online/blob/3e642eb6bee265c6d51517a392a823ced93f9b6b/common/src/main/java/me/johnnywoof/ao/utils/CheckMethods.java#L25
SessionServerStatus is checking `https://authserver.mojang.com/` not `https://sessionserver.mojang.com/`.
Can you fix it?

**Comment by Pantera07** [comment]
https://github.com/Dablakbandit/always-online/commit/762c3e3fb826de874845c0b007fc0fa9522a28d6
Why did this change?

**Comment by Pantera07** [comment]
https://github.com/Dablakbandit/always-online/pull/17
This is not tested. If it looks good to you, merge it.

**Comment by TheKrafter** [comment]
Why does this check `/session/minecraft/profile/069a79f444e94726a5befca90e38aaf5` and not just the server status itself?

**Comment by Pantera07** [comment]
I think this plugin is no longer maintained.

**Comment by Dablakbandit** [comment]
Plugin still works as intended
